---
- name: Crear vulnerabilidades en windows
  hosts: rdp
  gather_facts: no
  tasks:
    - name: Descargar el instalador de XAMPP
      win_get_url:
        url: https://sourceforge.net/projects/xampp/files/XAMPP%20Windows/7.4.28/xampp-windows-x64-7.4.28-1-VC15-installer.exe/download
        dest: C:\temp\xampp-installer.exe

    - name: Instalar XAMPP
      win_command: C:\temp\xampp-installer.exe --mode unattended
      args:
        creates: C:\xampp

    - name: Desplegar wordpress
      win_copy:
        src: ./web/wordpress-4.6.zip
        dest: C:\xampp\htdocs\wordpress-4.6.zip
    - name: Establecer la variable de entorno PATH
      win_path:
        elements:
          - "C:\\Program Files\\7-Zip\\"
        state: present

    - name: Descomprimir la app
      win_command: 7z x "C:\xampp\htdocs\wordpress-4.6.zip" -oC:\xampp\htdocs\"

    - name: Iniciar servicios
      win_command: C:\xampp\apache_start.bat
    
    - name: Iniciar servicios
      win_command: C:\xampp\mysql_start.bat

#----------------------------
#    - name: Descargar el instalador de 7-Zip
#      win_get_url:
#        url: https://www.7-zip.org/a/7z1900-x64.msi
#        dest: C:\temp\7z1900-x64.msi
#
#    - name: Instalar 7-Zip
#      win_package:
#        path: C:\temp\7z1900-x64.msi
#        state: present
#      register: install_result
#
#    - name: Verificar si 7-Zip está instalado
#      win_stat:
#        path: C:\Program Files\7-Zip
#      register: installed_check
#
#    - name: Mostrar mensaje de éxito
#      debug:
#        msg: "7-Zip se ha instalado correctamente."
#      when: installed_check.stat.exists
#-------------------
#v    - name: Copiar el archivo MSI al sistema Windows
#v      win_copy:
#v        src: ./deb/xampp-portable-win32-7.0.4-0-VC14-installer.msi   # Ruta local en el servidor Ansible
#v        dest: C:\temp\xampp-portable-win32-7.0.4-0-VC14-installer.msi 
#v
#v    - name: Instalar el archivo MSI
#v      win_package:
#v        path: C:\temp\xampp-portable-win32-7.0.4-0-VC14-installer.msi 
#v        state: present
#v      register: install_result
#v
#v    - name: Verificar si la instalación fue exitosa
#v      debug:
#v        msg: "La instalación fue exitosa."
#v      when: install_result.changed
#v
#    - name: Mostrar mensaje de éxito
#      win_msi:
#        path: 


#  tasks:
#    - name: Descaga XAMP
#      win_msi:
#        path: ./deb/xampp-portable-win32-7.0.4-0-VC14-installer.msi
#    
#    - name: Download the 7-Zip package
#      win_get_url:
#        url: https://www.7-zip.org/a/7z1701-x64.msi
#        dest: C:\temp\7z.msi
#    
#    - name: Ensure 7-Zip is installed through win_command
#      win_command: C:\Windows\System32\msiexec.exe /i C:\temp\7z.msi /qn /norestart
#      when: 7zip_installed.exists == false
#    
#    - name: Desplegar wordpress
#      ansible.windows.win_copy:
#        src: ./deb/wordpress-4.6.zip
#        dest: C:\xampp\htdocs
#    
#    - name: descomprimir la pp
#      win_command: tar -xf C:\xampp\htdocs\wordpress-4.6.zip
#    
#    - name: Reiniciamos servicios
#      ansible.windows.win_service:
#        name: httpd
#        state: restarted
#    
#    - name: Reiniciamos servicios de MySQL
#      ansible.windows.win_service:
#        name: mysqld
#        state: restarted
      
