---
- name: Install Tomcat
  hosts: tom
  become: true
  tasks:
    - name: Install Java
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: Download Tomcat
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz"
        dest: /opt/
    - name: Extract Tomcat
      unarchive:
        src: /opt/apache-tomcat-9.0.54.tar.gz
        dest: /opt/
        remote_src: yes
    - name: COnfiguración de usuarios
      ansible.builtin.copy:
        src: ./web/USER.xml
        dest: /opt/apache-tomcat-9.0.54/conf/tomcat-users.xml
    - name: Start Tomcat Service
      service:
        name: tomcat
        state: started
        enabled: yes
